language: node_js
node_js:
  - lts/*
script:
  - npm run test
before_deploy:
  - npm run build
deploy:
  provider: npm
  email: msk1361@gmail.com
  api_key:
    secure: faA9IYI0sgiplXzK5m0pVcc7nLmT2dtrIcCaF2kacpXF1KeRMgpTlzLzfdpwvDcUDZz3r7gSQ7W300YFv8rQTtSm733RynjWfoHDa2zPukFMNeqg9VVpx+KtqM+rxuQB+OYO0RJU72quN8dq78WPuNacPm8J7E8zIphzEiDeKpaCI3VmOysp8L0mk+xNs0iZTC8YTdNAgzExHjaxcI+NA3CVttXJYrAs8NypDy0wqsqj+POvPJggrUc1U5J9yS/J3HD+qrsTxAjkV53TCVujK0TB5VOZcBaYfKcfx+Inj0Np+dwQZWpRutEZ3kX7GS/BVZdRx3b1WfTKakHYZfPcBr4emxA6dAE5mxhSPo76cvWZ3soRxvf45O574uRGdyv8ySq8250ahrbztWAntNzT7pk+0X0NP2x8fBrwj2JryzL30qkwn++DeCPZ6X5DbDFA3Vk7zi8K1q5/HPIohZ/j1aaphjRP8mTZDxIZkOb7pG7anK3qALBZWsigSApYsXhiAItBuSZCX+Np3GLqYjAHgezQo3sFYlqXCd1SalrSKOHeFbHJ5Cso3hVhtCPrA7ZuwR59SLr5PWp+t7rfpHuE9QXjNtPrV4EaepZvRMhGf3rxv1AOALOUJ6VTW5QKdlYyax2klUjifkLckRUCgC89lxW8898xKyYa3CJgbJQbp9E=
  skip_cleanup: true
  on:
    tags: true
    repo: mehdisadeghi/react-mathjax-preview
