name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    name: Publish demo website
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - run: yarn install
    - run: yarn run parcel build --target demo --no-optimize index.html --dist-dir dist/demo --public-url https://mehdisadeghi.github.io/react-mathjax-preview
    - run: touch dist/demo/.nojekyll

    - name: Deploy page
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        folder: dist/demo
